preserve_hierarchy: false
files:
  - source: '**/*.*'
    ignore:
      - themes/**/*.ejs
      - '*.js'
      - .*
      - src/_posts/**/*.*
      - '*.styl'
      - icons/*.*
      - package.json
      - package-lock.json
    translation: '%original_path%/%original_file_name%'
