---
title: Vue.js
subtitle: ""
description: "Framework JavaScript linh động"
author: Evan You
email: ""
language: ""
url: 'https://vi.vuejs.org'
root: /
permalink: ':year/:month/:day/:title/'
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
source_dir: src
public_dir: public
new_post_name: ':title.md'
default_layout: post
auto_spacing: false
titlecase: false
external_link: true
max_open_file: 100
multi_thread: true
filename_case: 0
render_drafts: false
post_asset_folder: false
highlight:
  enable: true
  line_number: false
  tab_replace: ""
default_category: uncategorized
category_map: ""
tag_map: ""
archive: 0
category: 0
tag: 0
port: 4000
logger: false
logger_format: ""
date_format: MMM D YYYY
time_format: 'H:mm:ss'
per_page: 10
pagination_dir: page
disqus_shortname: ""
theme: vue
exclude_generator: ""
markdown:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true
offline:
  maximumFileSizeToCacheInBytes: 10485760
  staticFileGlobs:
    - public/**/*.{js,html,css,png,jpg,jpeg,gif,svg,eot,ttf,woff,woff2,json,xml}
  stripPrefix: public
  verbose: true
  runtimeCaching:
    - 
      urlPattern: /*
      handler: networkFirst
      options:
        origin: sendgrid.sp1.convertro.com
    - 
      urlPattern: /*
      handler: networkFirst
      options:
        origin: ad.doubleclick.net
    - 
      urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdn.jsdelivr.net
    - 
      urlPattern: /*
      handler: cacheFirst
      options:
        origin: fonts.googleapis.com
    - 
      urlPattern: /*
      handler: cacheFirst
      options:
        origin: fonts.gstatic.com
    - 
      urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdnjs.cloudflare.com
    - 
      urlPattern: /*
      handler: cacheFirst
      options:
        origin: maxcdn.bootstrapcdn.com
deploy:
  type: git
  repository: 'git@github.com:vuejs-vn/vuejs.org.git'
feed:
  type: atom
  path: atom.xml
  limit: 20
alias:
  api/index.html: v2/api/index.html
  guide/class-and-style.html: v2/guide/class-and-style.html
  guide/comparison.html: v2/guide/comparison.html
  guide/components.html: v2/guide/components.html
  guide/computed.html: v2/guide/computed.html
  guide/conditional.html: v2/guide/conditional.html
  guide/custom-directive.html: v2/guide/custom-directive.html
  guide/deployment.html: v2/guide/deployment.html
  guide/events.html: v2/guide/events.html
  guide/forms.html: v2/guide/forms.html
  guide/index.html: v2/guide/index.html
  guide/installation.html: v2/guide/installation.html
  guide/instance.html: v2/guide/instance.html
  guide/join.html: v2/guide/join.html
  guide/list.html: v2/guide/list.html
  guide/migration-vue-router.html: v2/guide/migration-vue-router.html
  guide/migration-vuex.html: v2/guide/migration-vuex.html
  guide/migration.html: v2/guide/migration.html
  guide/mixins.html: v2/guide/mixins.html
  guide/plugins.html: v2/guide/plugins.html
  guide/reactivity.html: v2/guide/reactivity.html
  guide/render-function.html: v2/guide/render-function.html
  guide/routing.html: v2/guide/routing.html
  guide/single-file-components.html: v2/guide/single-file-components.html
  guide/ssr.html: v2/guide/ssr.html
  guide/state-management.html: v2/guide/state-management.html
  guide/syntax.html: v2/guide/syntax.html
  guide/transitioning-state.html: v2/guide/transitioning-state.html
  guide/transitions.html: v2/guide/transitions.html
  guide/unit-testing.html: v2/guide/unit-testing.html
  examples/commits.html: v2/examples/commits.html
  examples/elastic-header.html: v2/examples/elastic-header.html
  examples/firebase.html: v2/examples/firebase.html
  examples/grid-component.html: v2/examples/grid-component.html
  examples/hackernews.html: v2/examples/hackernews.html
  examples/index.html: v2/examples/index.html
  examples/modal.html: v2/examples/modal.html
  examples/select2.html: v2/examples/select2.html
  examples/svg.html: v2/examples/svg.html
  examples/todomvc.html: v2/examples/todomvc.html
  examples/tree-view.html: v2/examples/tree-view.html

